name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
    
  # calendar-view:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     # must have this permission!!
  #     contents: write 
  #   steps:
  #     - uses: lowlighter/metrics@latest
  #       with:
  #         filename: fullyear.svg
  #         token: ${{ secrets.METRICS_TOKEN }}
  #         base: ""
  #         plugin_isocalendar: yes
  #         plugin_isocalendar_duration: full-year
  
  # line-contribution:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     # must have this permission!!
  #     contents: write 
  #   steps:
  #   - uses: lowlighter/metrics@latest
  #     with:
  #       filename: lines-history.svg
  #       token: ${{ secrets.METRICS_TOKEN }}
  #       base: ""
  #       plugin_lines: yes
  #       plugin_lines_sections: repositories, history
  #       plugin_lines_repositories_limit: 4
  #       plugin_lines_history_limit: 1

  most-used-lang:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: unw9527
          base: ''
          base_indepth: yes
          filename: most-used-lang.svg
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, less, dockerfile, makefile, qmake, lex, cmake,
            gnuplot
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_languages_indepth: no
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: programming
